/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArtistRouteImport } from './routes/artist'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as ChartsRouteImport } from './routes/charts'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LikedRouteImport } from './routes/liked'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as AlbumAlbumIdRouteImport } from './routes/album.$albumId'
import { Route as GenreGenreIdRouteImport } from './routes/genre.$genreId'
import { Route as PlaylistPlaylistIdRouteImport } from './routes/playlist.$playlistId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistRoute = ArtistRouteImport.update({
  id: '/artist',
  path: '/artist',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartsRoute = ChartsRouteImport.update({
  id: '/charts',
  path: '/charts',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LikedRoute = LikedRouteImport.update({
  id: '/liked',
  path: '/liked',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumAlbumIdRoute = AlbumAlbumIdRouteImport.update({
  id: '/album/$albumId',
  path: '/album/$albumId',
  getParentRoute: () => rootRouteImport,
} as any)
const GenreGenreIdRoute = GenreGenreIdRouteImport.update({
  id: '/genre/$genreId',
  path: '/genre/$genreId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistPlaylistIdRoute = PlaylistPlaylistIdRouteImport.update({
  id: '/playlist/$playlistId',
  path: '/playlist/$playlistId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artist': typeof ArtistRoute
  '/browse': typeof BrowseRoute
  '/charts': typeof ChartsRoute
  '/library': typeof LibraryRoute
  '/liked': typeof LikedRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
  '/album/$albumId': typeof AlbumAlbumIdRoute
  '/genre/$genreId': typeof GenreGenreIdRoute
  '/playlist/$playlistId': typeof PlaylistPlaylistIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artist': typeof ArtistRoute
  '/browse': typeof BrowseRoute
  '/charts': typeof ChartsRoute
  '/library': typeof LibraryRoute
  '/liked': typeof LikedRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
  '/album/$albumId': typeof AlbumAlbumIdRoute
  '/genre/$genreId': typeof GenreGenreIdRoute
  '/playlist/$playlistId': typeof PlaylistPlaylistIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/artist': typeof ArtistRoute
  '/browse': typeof BrowseRoute
  '/charts': typeof ChartsRoute
  '/library': typeof LibraryRoute
  '/liked': typeof LikedRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
  '/album/$albumId': typeof AlbumAlbumIdRoute
  '/genre/$genreId': typeof GenreGenreIdRoute
  '/playlist/$playlistId': typeof PlaylistPlaylistIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/artist'
    | '/browse'
    | '/charts'
    | '/library'
    | '/liked'
    | '/search'
    | '/settings'
    | '/sources'
    | '/album/$albumId'
    | '/genre/$genreId'
    | '/playlist/$playlistId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/artist'
    | '/browse'
    | '/charts'
    | '/library'
    | '/liked'
    | '/search'
    | '/settings'
    | '/sources'
    | '/album/$albumId'
    | '/genre/$genreId'
    | '/playlist/$playlistId'
  id:
    | '__root__'
    | '/'
    | '/artist'
    | '/browse'
    | '/charts'
    | '/library'
    | '/liked'
    | '/search'
    | '/settings'
    | '/sources'
    | '/album/$albumId'
    | '/genre/$genreId'
    | '/playlist/$playlistId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtistRoute: typeof ArtistRoute
  BrowseRoute: typeof BrowseRoute
  ChartsRoute: typeof ChartsRoute
  LibraryRoute: typeof LibraryRoute
  LikedRoute: typeof LikedRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  SourcesRoute: typeof SourcesRoute
  AlbumAlbumIdRoute: typeof AlbumAlbumIdRoute
  GenreGenreIdRoute: typeof GenreGenreIdRoute
  PlaylistPlaylistIdRoute: typeof PlaylistPlaylistIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artist': {
      id: '/artist'
      path: '/artist'
      fullPath: '/artist'
      preLoaderRoute: typeof ArtistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charts': {
      id: '/charts'
      path: '/charts'
      fullPath: '/charts'
      preLoaderRoute: typeof ChartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/liked': {
      id: '/liked'
      path: '/liked'
      fullPath: '/liked'
      preLoaderRoute: typeof LikedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/album/$albumId': {
      id: '/album/$albumId'
      path: '/album/$albumId'
      fullPath: '/album/$albumId'
      preLoaderRoute: typeof AlbumAlbumIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genre/$genreId': {
      id: '/genre/$genreId'
      path: '/genre/$genreId'
      fullPath: '/genre/$genreId'
      preLoaderRoute: typeof GenreGenreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlist/$playlistId': {
      id: '/playlist/$playlistId'
      path: '/playlist/$playlistId'
      fullPath: '/playlist/$playlistId'
      preLoaderRoute: typeof PlaylistPlaylistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtistRoute: ArtistRoute,
  BrowseRoute: BrowseRoute,
  ChartsRoute: ChartsRoute,
  LibraryRoute: LibraryRoute,
  LikedRoute: LikedRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  SourcesRoute: SourcesRoute,
  AlbumAlbumIdRoute: AlbumAlbumIdRoute,
  GenreGenreIdRoute: GenreGenreIdRoute,
  PlaylistPlaylistIdRoute: PlaylistPlaylistIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
